version: 2

jobs:
  # test-3.7: &test-template
  build:
    docker:
      - image: circleci/python:3.7.0

      working_directory: ~/repo

      steps:
        - checkout

        - restore_cache:
            keys:
            - v1-dependencies-{{ checksum "setup.py" }}
            - v1-dependencies-

        - run:
            name: install dependencies
            command: |
              python3 -m venv venv
              . venv/bin/activate
              pip install -e .[dev]

        - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "requirements.txt" }}

        - run:
            name: run tests
            command: |
              . venv/bin/activate
              pytest --disable-pytest-warnings

        - store_artifacts:
            path: test-reports
            destination: test-reports

  # test-3.6:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.6-jessie
  # test-3.5:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.5-jessie
  # test-3.4:
  #   <<: *test-template
  #   docker:
  #     - image: circleci/python:3.5-jessie

# workflows:
#   version: 2
#   test:
#     jobs:
#       - test-3.7
#       - test-3.6
#       - test-3.5
#       - test-3.4
